hydra:
  run:
    dir: outputs/${trainer.model_name}/${data.data_name}/${task}/${run_id}
  job:
    chdir: true

seed: 1234
logger_level: INFO

task: offline
stage: ???
data_dir: ???
resume: false
run_id: ${generate_id:}
resume_id: ""
num_gts: 10

defaults:
  - /personalized_offline/data/perfrdiff_rewrite_weight@data
  - /personalized_offline/trainer/perfrdiff_rewrite_weight@trainer
  - /shared/logger: none
  - /shared/path@path
  - _self_
